# legal_ai_agent/monitoring/alertmanager.yml

global:
  resolve_timeout: 5m

route:
  receiver: 'slack-alerts'
  # за потреби можна додати group_by, group_wait, group_interval тощо

receivers:
  - name: 'slack-alerts'
    slack_configs:
      - api_url: '${SLACK_API_URL}'
        channel: '#alerts'
        send_resolved: true